let g:coc_global_extensions = ['coc-prettier',
      \ 'coc-marketplace',
      \ 'coc-explorer',
      \ 'coc-emoji',
      \ 'coc-tsserver',
      \ 'coc-json',
      \ 'coc-css',
      \ 'coc-clangd',
      \ 'coc-lua',
      \ 'coc-texlab',
      \ ]
